/*
 * Hero - Shoutcast and Icecast Radio Player With History - v3.3
 * Copyright 2017-2020, LambertGroup
 *
 */

 (function(c){function J(a,b,f,e){c(a.thumbsHolder_Thumbs[a.current_img_no]).css({background:b.playlistRecordBgOnColor,"border-bottom-color":b.playlistRecordBottomBorderOnColor,color:b.playlistRecordTextOnColor});a.is_very_first||M(-1,a,b,f);if(""!=b.radio_stream)var l=b.radio_stream;return l}function T(a){var b=new XMLHttpRequest;b.open("HEAD",a,!1);b.send();console.log(a+"   ----   "+b.status);return 404!=b.status}function U(a,b,f,e){var l=b.noImageAvailable,m="",w="";if(""!=a&&void 0!=a){m=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];
 if("jpg"==m||"jpeg"==m||"JPG"==m||"JPEG"==m)w="&iiurlparam=qlow-1000px";c.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+w,{},function(a){""!=c("ii",a).attr("thumburl")&&void 0!=c("ii",a).attr("thumburl")?(l=c("ii",a).attr("thumburl"),f.wiki_photo_path=l):""!=c("ii",a).attr("url")&&void 0!=c("ii",a).attr("url")&&(l=c("ii",a).attr("url"),f.wiki_photo_path=l);O(b,f,e,l)})}}function P(a,b,f,e,l,m,w,r,n,u,p,q,t,A,v,y,g,h){var C=
 f.noImageAvailable,k="",B="";if(""!=f.optional_images_path)b.playlist_images_arr[h]=a;else if(""!=a&&void 0!=a){k=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];if("jpg"==k||"jpeg"==k||"JPG"==k||"JPEGs"==k)B="&iiurlparam=qlow-200px";c.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+B,{},function(a){""!=c("ii",a).attr("thumburl")&&void 0!=c("ii",a).attr("thumburl")?C=c("ii",a).attr("thumburl"):""!=c("ii",a).attr("url")&&void 0!=c("ii",
 a).attr("url")&&(C=c("ii",a).attr("url"));b.playlist_images_arr[h]=C})}0!==(h+1)%3&&h!=b.playlist_arr.length-1||setTimeout(function(){K(b,f,e,l,m,w,r,n,u,p,q,t,A,v,y,g)},1E3)}function N(a){var b;a=a.split("");a.forEach(function(f,e){b="\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00df\u00d2\u00d3\u00d4\u00d5\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00f0\u00c7\u00e7\u00d0\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00d1\u00f1\u0160\u0161\u0178\u00ff\u00fd\u017d\u017e\u2019".indexOf(f);
 -1!=b&&(a[e]="AAAAAAaaaaaaBOOOOOOOooooooEEEEeeeeeCcDIIIIiiiiUUUUuuuuNnSsYyyZz'"[b])});return a.join("").trim()}function G(a,b){var f=new XMLHttpRequest;f.open(a.method,"https://zet.pluginsandthemes.ro/"+a.url);f.onload=f.onerror=function(){b(a.method+" "+a.url+"\n"+f.status+" "+f.statusText+"\n\n"+(f.responseText||""))};/^POST/i.test(a.method)&&(f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.setRequestHeader("X-Requested-With","XMLHttpRequest"));f.send(a.data)}function Q(a,
 b,f,e,c,m,w,r,n,u,p,q,t,A,v,y){""!=a.curTitle&&a.isHistoryGenerated&&a.prevTitle!=a.curTitle&&(""!=a.prevTitle&&(30<=a.gen_total_images&&(a.gen_total_images--,a.playlist_arr.pop(),a.playlist_images_arr.pop()),a.gen_total_images++,a.playlist_arr.unshift(a.prevTitle),a.playlist_images_arr.unshift(a.prev_song_image),K(a,b,f,e,c,m,w,r,n,u,p,q,t,A,v,y)),a.prevTitle=a.curTitle)}function L(a,b,f,e,c,m,w,r,n,u,p,q,t,A,v,y){if(b.showOnlyPlayButton||a.isRadiojar||""!=b.azuracast_api_nowplaying_url)a.isRadiojar&&
 G({method:"GET",url:"http://www.radiojar.com/api/stations/"+a.mount_point+"/now_playing/?my_rand="+Math.random()},function(h){startPoint=h.indexOf("{");-1!==startPoint&&(lengthPoint=h.length,h=h.substr(startPoint,lengthPoint),h=JSON.parse(h),a.curTitle=h.artist+" - "+h.title,E(a,b,f,m,w,r,n,u,p,q,t),Q(a,b,m,f,e,c,A,w,r,n,u,p,q,t,v,y))}),""!=b.azuracast_api_nowplaying_url&&G({method:"GET",url:b.azuracast_api_nowplaying_url+"?my_rand="+Math.random()},function(h){var g=h.indexOf("{");if(-1!==g){var k=
 h.length;h=h.substr(g,k);h=JSON.parse(h);a.curTitle=h.now_playing.song.text;E(a,b,f,m,w,r,n,u,p,q,t);Q(a,b,m,f,e,c,A,w,r,n,u,p,q,t,v,y)}});else{if(""!=b.metadata_file_type||""!=b.azuracast_api_nowplaying_url)if(a.now_playing_found=!0,a.now_playing_current_k=b.metadata_file_type-1,""==a.ip||void 0==a.ip)a.ip=1;!1===a.now_playing_found&&a.now_playing_current_k<a.now_playing_arr_lenght&&a.now_playing_current_k++;var g=a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+
 ("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"?my_rand="+Math.random():"");0===a.now_playing_current_k&&(g=a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"&my_rand="+Math.random():""));""!=b.url_custom_metdata_file&&(g=b.url_custom_metdata_file);""!=a.ip&&a.now_playing_current_k<a.now_playing_arr_lenght?(G({method:"GET",url:g},function(h){var g="";switch(a.now_playing_current_k){case 0:if(-1!=h.indexOf("<SONGTITLE>")){a.now_playing_found=
 !0;var k=h.indexOf("<SONGTITLE>")+11;var l=h.indexOf("</SONGTITLE>")-k;g=h.substr(k,l);a.curTitle=g;E(a,b,f,m,w,r,n,u,p,q,t)}else L(a,b,f,e,c,m,w,r,n,u,p,q,t,A,v,y);break;case 1:k=h.indexOf("<body>")+6;l=h.length;h=h.substr(k,l);h=h.replace("</body></html>","");g=h.split(",");""!=g[6]&&void 0!=g[6]&&"oracle:0"!=g[6]?(a.now_playing_found=!0,g=g[6],a.curTitle=g,E(a,b,f,m,w,r,n,u,p,q,t)):L(a,b,f,e,c,m,w,r,n,u,p,q,t,A,v,y);break;case 2:k=h.indexOf('{"icestats":');if(-1!==k){l=h.length;h=h.substr(k,l);
 h=JSON.parse(h);k=!1;for(var z=0;z<Object.keys(h.icestats.source).length&&!k;)l=h.icestats.source[z].listenurl,0<l.indexOf(a.mount_point)&&(k=!0,z--),z++;k&&""!=h.icestats.source[z].title&&void 0!=h.icestats.source[z].title&&(a.now_playing_found=!0,g=h.icestats.source[z].title,a.curTitle=g,E(a,b,f,m,w,r,n,u,p,q,t))}""==g&&(a.now_playing_found=!1,L(a,b,f,e,c,m,w,r,n,u,p,q,t,A,v,y));break;case 3:""!=a.mount_point&&(k=h.indexOf(a.mount_point));0<k&&(l=h.length,h=h.substr(k,l));l=h.indexOf("Currently playing:");
 -1==l&&(l=h.indexOf("Current Song:"));0<l&&(a.now_playing_found=!0,k=h.indexOf('<td class="streamstats">',l),k=0<k?k+24:h.indexOf('<td class="streamdata">',l)+23,l=h.indexOf("</td>",k),g=h.substr(k,l-k),a.curTitle=g,E(a,b,f,m,w,r,n,u,p,q,t));""==g&&(a.now_playing_found=!1,L(a,b,f,e,c,m,w,r,n,u,p,q,t,A,v,y));break;default:a.now_playing_found=!0,a.curTitle="Not available...",E(a,b,f,m,w,r,n,u,p,q,t)}}),Q(a,b,m,f,e,c,A,w,r,n,u,p,q,t,v,y)):(curSong="Data not available...",a.curTitle=curSong,E(a,b,f,m,
 w,r,n,u,p,q,t))}}function R(a,b,f,e,l,m,w,r,n,u,p,q,t,A,v,y,g){b.grabLastFmPhoto&&(a.musicbrainzHistory_setTimeout_arr[g]=setTimeout(function(){var h=a.playlist_arr[g].split("-");h[0]=h[0].trim();a.the_artist_id_history_arr[g]="";a.the_wikidata_id_history_arr[g]="";var C=b.noImageAvailable;a.wiki_photo_path=C;clearTimeout(a.musicbrainzHistory_setTimeout_arr[g]);h[0]=h[0].trim();if(""!=b.optional_images_path){var k=b.optional_images_path+a.playlist_arr[g]+".jpg";k=encodeURI(k);k=k.replace("(","%28");
 k=k.replace(")","%29");k=k.replace("&apos;","%27");k=k.replace("&amp;","%26");T(k)||(k=b.noImageAvailable);P(k,a,b,e,f,t,q,A,l,m,w,r,n,u,p,v,y,g)}else c.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+h[0],{},function(k){var z="",d,x="";a.the_artist_id_history_arr[g]="";var B=h[0];B=B.toLowerCase();B=N(B);c("artist",k).each(function(){d=c("name",this)[0];0<c("name",this).length&&""==a.the_artist_id_history_arr[g]&&(z=c(d).text(),z=z.toLowerCase(),z=N(z),B.toLowerCase()==z.toLowerCase()&&
 (a.the_artist_id_history_arr[g]=c(this).attr("id")))});""==a.the_artist_id_history_arr[g]&&"ROCK RADIO"!=h[0]&&(a.the_artist_id_history_arr[g]=c(c("artist",k)[0]).attr("id"));""!=a.the_artist_id_history_arr[g]&&void 0!=a.the_artist_id_history_arr[g]&&(a.musicbrainzHistory_setTimeout_arr[g]=setTimeout(function(){a.the_wikidata_id_history_arr[g]="";c.get("https://musicbrainz.org/ws/2/artist/"+a.the_artist_id_history_arr[g]+"?inc=url-rels",{},function(d){c("relation",d).each(function(){"image"==c(this).attr("type")&&
 0<c("target",this).length&&(x=c("target",this).text(),x=x.substr(x.indexOf("File:",10)+5,x.length),P(x,a,b,e,f,t,q,A,l,m,w,r,n,u,p,v,y,g));"wikidata"==c(this).attr("type")&&0<c("target",this).length&&""==x&&(a.the_wikidata_id_history_arr[g]=c("target",this).text(),a.the_wikidata_id_history_arr[g]=a.the_wikidata_id_history_arr[g].substr(a.the_wikidata_id_history_arr[g].indexOf("/Q",10)+1,a.the_wikidata_id_history_arr[g].length),c.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+
 a.the_wikidata_id_history_arr[g]+"&property=P18&format=xml&origin=*",{},function(d){x=c("datavalue",c("mainsnak",d)).attr("value");P(x,a,b,e,f,t,q,A,l,m,w,r,n,u,p,v,y,g)}))});if(""==x||void 0==x)a.playlist_images_arr[g]=C})},3E3*(g+1)))})},3E3*(g+1)))}function Y(a,b,f,c,l,m,w,r,n,u,p,q,t,A,v,y,g){clearInterval(a.radioReaderAjaxInterval);if(-1!==b.radio_stream.indexOf("radiojar.com")){a.isRadiojar=!0;var e=b.radio_stream.match(a.myregexp_radiojar);null!=e&&(a.http_or_https=e[1],a.ip=e[2],a.mount_point=
 e[3],a.port="")}else-1==b.radio_stream.indexOf("/",9)&&(b.radio_stream+="/;"),"/"==b.radio_stream.charAt(b.radio_stream.length-1)&&(b.radio_stream+=";"),e=b.radio_stream.match(a.myregexp),null!=e&&(a.http_or_https=e[1],a.ip=e[2],a.port=e[3],a.mount_point=e[4],";"==a.mount_point.trim()&&(a.mount_point=""));p.css({width:b.playerWidth+"px",height:b.imageHeight+"px",background:"url("+b.noImageAvailable+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});
 if(!b.showOnlyPlayButton){L(a,b,f,t,q,c,l,m,w,r,n,u,p,A,v,y);a.radioReaderAjaxInterval=setInterval(function(){L(a,b,f,t,q,c,l,m,w,r,n,u,p,A,v,y)},1E3*b.nowPlayingInterval);a.playlist_arr=[];a.playlist_images_arr=[];var C=-1,k,B,z,d=0;a.isRadiojar&&G({method:"GET",url:"http://www.radiojar.com/api/stations/"+a.mount_point+"/tracks/?my_rand="+Math.random()},function(e){k=e.indexOf("[{");if(-1!==k){B=e.length;e=e.substr(k,B);var h=JSON.parse(e);h.reverse()}for(d=0;d<Object.keys(h).length;d++)""!=h[d].track&&
 "Empty Title"!=h[d].track&&(C++,a.playlist_arr[C]=h[d].artist+" - "+h[d].track,a.playlist_images_arr[C]=b.noImageAvailable,R(a,b,f,c,l,m,w,r,n,u,p,q,t,A,v,y,C));a.playlist_arr.length?K(a,b,c,f,t,q,A,l,m,w,r,n,u,p,v,y):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&g.click()});""!=b.azuracast_api_nowplaying_url&&G({method:"GET",url:b.azuracast_api_nowplaying_url+"?my_rand="+Math.random()},function(e){k=e.indexOf("{");if(-1!==k){B=e.length;e=e.substr(k,B);e=JSON.parse(e);for(d=0;d<Object.keys(e.song_history).length;d++)""!=
 e.song_history[d].song.text&&"Empty Title"!=e.song_history[d].song.text.text&&(C++,a.playlist_arr[C]=e.song_history[d].song.text,a.playlist_images_arr[C]=b.noImageAvailable,R(a,b,f,c,l,m,w,r,n,u,p,q,t,A,v,y,C));a.playlist_arr.length?K(a,b,c,f,t,q,A,l,m,w,r,n,u,p,v,y):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&g.click()}});a.isRadiojar||""!=b.azuracast_api_nowplaying_url||b.iceCastFirst||G({method:"GET",url:a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.history_arr[a.history_current_k]},function(d){if(-1!=
 d.indexOf("Current Song"))for(k=d.indexOf("Current Song")+12,B=d.length,d=d.substr(k,B),z=d.split("</td><td>"),z.shift(),d=0;d<z.length;d++)k=z[d].indexOf("</"),-1!=k&&(B=k,z[d]=z[d].substr(0,B),z[d]=z[d].replace(/<\/?[^>]+(>|$)/g,""),""!=z[d]&&"Empty Title"!=z[d]&&(C++,a.playlist_arr[C]=z[d],a.playlist_images_arr[C]=b.noImageAvailable,R(a,b,f,c,l,m,w,r,n,u,p,q,t,A,v,y,C)));a.playlist_arr.length?K(a,b,c,f,t,q,A,l,m,w,r,n,u,p,v,y):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&g.click()})}a.isFlashNeeded?
 ""!=a.myFlashObject&&a.myFlashObject.myAS3function(J(a,b,f,c),b.initialVolume):(document.getElementById(a.audioID).src=J(a,b,f,c),document.getElementById(a.audioID).load(),b.autoPlay&&l.click())}function O(a,b,c,e){c.css({background:"url("+e+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});b.prev_song_image=b.cur_song_image;b.cur_song_image=e}function E(a,b,f,e,l,m,w,r,n,u,p){a.curSongText="";b.showTitle&&null!=a.curTitle&&""!=a.curTitle&&
 (a.curSongText+=a.curTitle);b.showRadioStation&&null!=b.radio_name&&""!=b.radio_name&&n.html(b.radio_name);var q=a.curTitle.split("-"),t=b.noImageAvailable;q[0]=q[0].trim();3<=q.length&&(q[0]=q[0].trim()+"-"+q[1].trim());if(b.grabLastFmPhoto&&""!=q[0].trim()){var A,v="",y,g="";a.the_artist_id="";a.the_wikidata_id="";t=b.noImageAvailable;a.wiki_photo_path=t;clearTimeout(a.musicbrainz_setTimeout);clearTimeout(a.no_artist_image_setTimeout);q[0]=q[0].trim();""!=q[0]&&void 0!=q[0]&&a.prevTitle!=a.curTitle&&
 (p.css({background:"url("+t+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"}),a.musicbrainz_setTimeout=setTimeout(function(){""!=b.optional_images_path?(g=b.optional_images_path+a.curTitle+".jpg",g=encodeURI(g),g=g.replace("(","%28"),g=g.replace(")","%29"),g=g.replace("&apos;","%27"),g=g.replace("&amp;","%26"),T(g)||(g=b.noImageAvailable),t=g,O(b,a,p,t)):c.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+q[0],{},function(e){a.the_artist_id=
 "";A=q[0];A=A.toLowerCase();A=N(A);c("artist",e).each(function(){y=c("name",this)[0];0<c("name",this).length&&""==a.the_artist_id&&(v=c(y).text(),v=v.toLowerCase(),v=N(v),A.toLowerCase()==v.toLowerCase()&&(a.the_artist_id=c(this).attr("id")))});""==a.the_artist_id&&"ROCK RADIO"!=q[0]&&(a.the_artist_id=c(c("artist",e)[0]).attr("id"));""!=a.the_artist_id&&void 0!=a.the_artist_id&&(a.musicbrainz_setTimeout=setTimeout(function(){a.the_wikidata_id="";c.get("https://musicbrainz.org/ws/2/artist/"+a.the_artist_id+
 "?inc=url-rels",{},function(e){c("relation",e).each(function(){"image"==c(this).attr("type")&&0<c("target",this).length&&(g=c("target",this).text(),g=g.substr(g.indexOf("File:",10)+5,g.length),U(g,b,a,p));"wikidata"==c(this).attr("type")&&0<c("target",this).length&&""==g&&(a.the_wikidata_id=c("target",this).text(),a.the_wikidata_id=a.the_wikidata_id.substr(a.the_wikidata_id.indexOf("/Q",10)+1,a.the_wikidata_id.length),c.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+a.the_wikidata_id+
 "&property=P18&format=xml&origin=*",{},function(e){g=c("datavalue",c("mainsnak",e)).attr("value");U(g,b,a,p)}))});a.no_artist_image_setTimeout=setTimeout(function(){""!=g&&void 0!=g||O(b,a,p,t)},1E3)})},1500))})},1500))}a.curSongText&&(f=a.curSongText.split("-"),a.curSongAuthorText=f[0].trim(),2<=f.length&&(a.curSongText=f[1].trim()),3<=f.length&&(a.curSongAuthorText=f[0].trim()+"-"+f[1].trim(),a.curSongText=f[2].trim()),m.html(V(a.curSongAuthorText,b)),r.css({width:"auto"}),a.isStationTitleInsideScrolling=
 !1,a.stationTitleInsideWait=0,r.stop(),r.css({"margin-left":0}),r.html(a.curSongText),clearInterval(a.timeupdateInterval),r.width()>a.titleWidth?a.timeupdateInterval=setInterval(function(){!a.isStationTitleInsideScrolling&&5<=a.stationTitleInsideWait&&r.width()>a.titleWidth?(a.isStationTitleInsideScrolling=!0,a.stationTitleInsideWait=0,r.html(a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),r.css({"margin-left":0}),r.stop().animate({"margin-left":b.playerWidth-
 r.width()+"px"},parseInt(1E4*(r.width()-b.playerWidth)/150,10),"linear",function(){a.isStationTitleInsideScrolling=!1})):!a.isStationTitleInsideScrolling&&r.width()>a.titleWidth&&a.stationTitleInsideWait++},300):r.css({width:"100%"}))}function M(a,b,f,e){if(b.gen_total_images>f.numberOfThumbsPerScreen){var l=(b.thumbsHolder_ThumbHeight+1)*(b.gen_total_images-f.numberOfThumbsPerScreen),m=0;e.stop(!0,!0);c("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()});
 -1==a||b.isCarouselScrolling?!b.isCarouselScrolling&&b.gen_total_images>f.numberOfThumbsPerScreen&&(b.isCarouselScrolling=!0,m=-1*parseInt((b.thumbsHolder_ThumbHeight+1)*b.current_img_no,10),Math.abs(m)>l&&(m=-1*l),b.gen_total_images>f.numberOfThumbsPerScreen&&f.showPlaylist&&b.audio6_html5_sliderVertical.slider("value",100+parseInt(100*m/l)),e.animate({top:m+"px"},500,"easeOutCubic",function(){b.isCarouselScrolling=!1;c("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})})):
 (b.isCarouselScrolling=!0,m=2>=a?-1*l:parseInt(l*(a-100)/100,10),0<m&&(m=0),e.animate({top:m+"px"},1100,"easeOutQuad",function(){b.isCarouselScrolling=!1;c("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})}))}}function S(a,b,c,e,l,m,w,r,n,u,p,q,t,A,v,y,g,h,C,k,B,z,d,x,F,D){e.width(c.playerWidth);if(c.showOnlyPlayButton||b.isMinified)a="none";"none"==a?v.css({width:"0px",height:"0px"}):v.css({width:c.playerWidth+"px",height:parseInt(c.playerWidth/c.origWidth*c.imageHeight,
 10)+"px"});c.sticky&&c.startMinified?v.css({display:"none",top:"0px",left:"0px"}):v.css({display:a,top:"0px",left:"0px"});b.imageTopPos=0;b.imageLeftPos=0;b.frameBehindTextTopPos=v.height();b.frameBehindTextLeftPos=0;c.showOnlyPlayButton?h.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:c.frameBehindTextColor,width:0,height:0}):h.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:c.frameBehindTextColor,height:n.height()+2*b.playVerticalPadding+
 "px"});b.playTopPos=b.frameBehindTextTopPos+b.playVerticalPadding;b.playLeftPos=b.frameBehindTextLeftPos+b.playHorizontalPadding;n.css({top:b.playTopPos+"px",left:b.playLeftPos+"px"});b.titleWidth=c.playerWidth-4*b.playHorizontalPadding-n.width();b.titleTopPos=b.playTopPos+3;b.titleLeftPos=n.width()+2*b.playHorizontalPadding;p.css({color:c.songTitleColor,top:b.titleTopPos+"px",left:b.titleLeftPos+"px",width:b.titleWidth+"px"});b.lineSeparatorTopPos=b.titleTopPos+p.height()+2;b.lineSeparatorLeftPos=
 b.titleLeftPos;C.css({background:c.lineSeparatorColor,top:b.lineSeparatorTopPos+"px",left:b.lineSeparatorLeftPos+"px",width:b.titleWidth+"px"});b.authorTopPos=b.lineSeparatorTopPos+8;b.authorLeftPos=b.titleLeftPos;u.css({color:c.authorTitleColor,top:b.authorTopPos+"px",left:b.authorLeftPos+"px",width:b.titleWidth+"px"});b.minimizeTopPos=b.playTopPos;!c.sticky||c.showOnlyPlayButton?(b.minimizeRightPos=0,B.css({display:"none",padding:0,margin:0})):c.sticky&&(b.minimizeRightPos=b.smallButtonDistance,
 B.css({top:b.minimizeTopPos+"px",right:b.minimizeRightPos+"px"}));b.frameBehindButtonsTopPos=b.frameBehindTextTopPos+h.height();b.frameBehindButtonsLeftPos=0;c.showOnlyPlayButton?k.css({background:c.frameBehindButtonsColor,height:0,top:b.frameBehindButtonsTopPos+"px",left:b.frameBehindButtonsLeftPos+"px"}):k.css({background:c.frameBehindButtonsColor,top:b.frameBehindButtonsTopPos+"px",left:b.frameBehindButtonsLeftPos+"px"});b.radioStationTopPos=b.frameBehindButtonsTopPos+Math.floor(k.height()-t.height())/
 2;b.radioStationLeftPos=b.playHorizontalPadding;t.css({color:c.radioStationColor,top:b.radioStationTopPos+"px",left:b.radioStationLeftPos+"px",width:b.titleWidth+"px"});0==b.historyButWidth&&(b.historyButWidth=z.width());b.showhidehistoryTopPos=b.frameBehindButtonsTopPos+Math.floor((k.height()-z.height())/2);b.temp_showHistoryBut?(b.showhideplaylistRightPos=2*b.smallButtonDistance,z.css({display:"block",width:b.historyButWidth+"px",top:b.showhidehistoryTopPos+"px",right:b.showhideplaylistRightPos+
 "px"})):(b.showhideplaylistRightPos=0,z.css({display:"none",width:0,padding:0,margin:0}));d.css({display:"none",width:0,padding:0,margin:0});b.volumeTopPos=b.frameBehindButtonsTopPos+Math.floor((k.height()-x.height())/2);c.showVolume?(b.volumeRightPos=b.showhideplaylistRightPos+z.width()+b.smallButtonDistance,x.css({top:b.volumeTopPos+"px",right:b.volumeRightPos+"px"})):(b.volumeRightPos=b.showhideplaylistRightPos+z.width(),x.css({display:"none",width:0,padding:0,margin:0}));b.twitterTopPos=b.frameBehindButtonsTopPos+
 Math.floor((k.height()-F.height())/2);c.showTwitterBut?(b.twitterRightPos=b.volumeRightPos+x.width()+b.smallButtonDistance,F.css({top:b.twitterTopPos+"px",right:b.twitterRightPos+"px"})):(b.twitterRightPos=b.volumeRightPos+x.width(),F.css({display:"none",width:0,padding:0,margin:0}));b.facebookTopPos=b.frameBehindButtonsTopPos+Math.floor((k.height()-D.height())/2);c.showFacebookBut?(b.facebookRightPos=b.twitterRightPos+F.width()+b.smallButtonDistance,D.css({top:b.facebookTopPos+"px",right:b.facebookRightPos+
 "px"})):(b.facebookRightPos=b.twitterRightPos,D.css({display:"none",width:0,padding:0,margin:0}))}function K(a,b,f,e,l,m,w,r,n,u,p,q,t,A,v,y){if(!b.showOnlyPlayButton){e.stop(!0,!0);a.isCarouselScrolling=!1;c(".readingData",m).css({display:"none"});r=parseInt(b.playerWidth/b.origWidth*b.historyRecordTitleLimit,10);n=parseInt(b.playerWidth/b.origWidth*b.historyRecordAuthorLimit,10);u=[];a.isHistoryGenerated=!0;e.html("");for(p=a.gen_total_images=0;p<a.playlist_arr.length;p++)a.gen_total_images++,u=
 a.playlist_arr[p].split("-"),1>u.length?a.gen_total_images--:(a.thumbsHolder_Thumb=c('<div class="thumbsHolder_ThumbOFF" rel="'+(a.gen_total_images-1)+'" data-origID="'+p+'"><div class="padding"><div class="img_div" style="background-image:url('+a.playlist_images_arr[p]+');background-color:#000000;"></div><span class="titlex">'+W(u[1],r,b)+'</span><span class="authorx">'+W(u[0],n,b)+"</span></div></div>"),e.append(a.thumbsHolder_Thumb),0==a.thumbsHolder_ThumbHeight&&(a.thumbsHolder_ThumbHeight=a.thumbsHolder_Thumb.height()),
 a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_ThumbHeight+1)*a.gen_total_images+"px",background:b.historyRecordBgColor,"border-bottom-color":b.historyRecordBottomBorderColor,color:b.historyRecordTextColor}),c(".titlex",a.thumbsHolder_Thumb).css({color:b.historyRecordSongColor,"border-bottom-color":b.historyRecordSongBottomBorderColor}),c(".authorx",a.thumbsHolder_Thumb).css({color:b.historyRecordAuthorColor}),a.current_img_no=0);l.height(2*b.historyPadding+(a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen+
 y.height()+b.historyPadding);m.height((a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen);m.css({"margin-top":y.height()+b.historyPadding+"px"});w.css({padding:b.historyPadding+"px"});a.thumbsHolder_Thumbs=c(".thumbsHolder_ThumbOFF",f);a.wrapperHeight=a.audioPlayerHeight+l.height()+b.historyTopPos;if(!b.showHistory||!b.showHistoryOnInit||0>l.css("margin-top").substring(0,l.css("margin-top").length-2))a.wrapperHeight=a.audioPlayerHeight;a.isMinified||v.css({height:a.wrapperHeight+"px"});a.gen_total_images>
 b.numberOfThumbsPerScreen&&b.showHistory?(b.isPlaylistSliderInitialized&&a.audio6_html5_sliderVertical.slider("destroy"),a.audio6_html5_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(c,f){M(f.value,a,b,e)}}),b.isPlaylistSliderInitialized=!0,a.audio6_html5_sliderVertical.css({display:"inline",position:"absolute",height:l.height()-20-3*b.historyPadding-y.height()+"px",left:f.width()-a.audio6_html5_sliderVertical.width()-b.historyPadding+"px",
 top:a.audioPlayerHeight+b.historyTopPos+2*b.historyPadding+2+y.height()+"px"}),b.showHistoryOnInit||a.audio6_html5_sliderVertical.css({opacity:0,display:"none"}),c(".thumbsHolder_ThumbOFF",f).css({width:f.width()-a.audio6_html5_sliderVertical.width()-2*b.historyPadding-3+"px"})):(b.isPlaylistSliderInitialized&&(a.audio6_html5_sliderVertical.slider("destroy"),b.isPlaylistSliderInitialized=!1),c(".thumbsHolder_ThumbOFF",f).css({width:f.width()-2*b.historyPadding+"px"}));m.mousewheel(function(c,f,l,
 k){c.preventDefault();c=a.audio6_html5_sliderVertical.slider("value");if(1<parseInt(c)&&-1==parseInt(f)||100>parseInt(c)&&1==parseInt(f))c+=3*f,a.audio6_html5_sliderVertical.slider("value",c),M(c,a,b,e)});e.css({top:"0px"})}}function V(a,b){b.preserveOriginalUpperLowerCase||(a=a.toLowerCase(),a=a.replace(/\b[a-z]/g,function(a){return a.toUpperCase()}),a=a.replace(/&Apos;/gi,"'"),a=a.replace(/&Amp;/gi,"&"),a=a.replace(/'[A-Z]/g,function(a){return a.toLowerCase()}));return a}function W(a,b,c){a=String(a);
 var e="";if(a.length>b){a=a.substring(0,b);var f=a.split(" ");a=a.substring(b-2,b-1);""!=a&&(f.pop(),e="...");a=f.join(" ")}a=V(a,c);return a+e}function Z(){c("audio").each(function(){c(".AudioPlay").removeClass("AudioPause");c(this)[0].pause()})}function X(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,c=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=c.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,c=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,
 null!=c.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function aa(a){var b=!1;document.getElementById(a.audioID).canPlayType&&"no"!=document.getElementById(a.audioID).canPlayType("audio/mpeg")&&""!=document.getElementById(a.audioID).canPlayType("audio/mpeg")||(b=!0);return b}var I=navigator.userAgent.toLowerCase();c.fn.audio6_html5=function(a){a=c.extend({},c.fn.audio6_html5.defaults,a);X();return this.each(function(){var b=c(this),f=c('<div class="frameBehindText"></div><div class="frameBehindButtons"></div> <div class="ximage"></div> <div class="AudioControls"> <a class="AudioCloseBut" title="Minimize"></a><a class="AudioFacebook" title="Facebook"></a><a class="AudioTwitter" title="Twitter"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div>   </div>   <div class="songTitle"><div class="songTitleInside"></div></div>  <div class="songAuthorLineSeparator"></div>  <div class="songAuthor"></div>  <div class="radioStation"></div>     <div class="thumbsHolderWrapper"><div class="historyPadding">  <div class="historyTitle"></div> <div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div></div>  <div class="slider-vertical"></div>'),
 e=b.parent(".audio6_html5");e.addClass(a.skin);e.append(f);var l=c(".frameBehindText",e),m=c(".frameBehindButtons",e);c(".AudioControls",e);var w=c(".AudioFacebook",e),r=c(".AudioTwitter",e),n=c(".AudioPlay",e),u=c(".AudioShowHidePlaylist",e),p=c(".VolumeButton",e),q=c(".VolumeSlider",e),t=c(".AudioCloseBut",e),A=c(".songTitle",e),v=c(".songTitleInside",e),y=c(".songAuthor",e),g=c(".songAuthorLineSeparator",e),h=c(".radioStation",e),C=c(".ximage",e),k=c(".historyTitle",e);e.wrap("<div class='the_wrapper'></div>");
 var B=e.parent(),z=X();if(-1!=I.indexOf("ipad")||-1!=I.indexOf("iphone")||-1!=I.indexOf("ipod")||-1!=I.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))a.autoPlay=!1;e.css({background:"transparent"});var d={current_img_no:0,origID:0,is_very_first:!0,total_images:0,gen_total_images:0,is_changeSrc:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",playlist_images_arr:"",isCarouselScrolling:!1,isHistoryGenerated:!1,isStationTitleInsideScrolling:!1,curTitle:"",prevTitle:"",cur_song_image:"",
 prev_song_image:"",curSongText:"",curSongAuthorText:"",stationTitleInsideWait:0,audioPlayerWidth:0,audioPlayerHeight:0,wrapperHeight:0,temp_showHistoryBut:!0,historyButWidth:0,isRadiojar:!1,historyInitialHeight:90,thumbsHolder_Thumb:c('<div class="thumbsHolder_ThumbOFF" rel="0"><div class="padding">test</div></div>'),thumbsHolder_ThumbHeight:0,thumbsHolder_Thumbs:"",constantDistance:0,titleWidth:0,radioStationTopPos:0,radioStationLeftPos:0,titleTopPos:0,titleLeftPos:0,lineSeparatorTopPos:0,lineSeparatorLeftPos:0,
 authorTopPos:0,authorLeftPos:0,minimizeTopPos:0,minimizeRightPos:0,isMinified:!1,imageTopPos:0,imageLeftPos:0,frameBehindButtonsTopPos:0,frameBehindButtonsLeftPos:0,frameBehindTextTopPos:0,frameBehindTextLeftPos:0,playTopPos:0,playLeftPos:0,volumeTopPos:0,volumeRightPos:0,volumesliderTopPos:0,volumesliderLeftPos:0,showhidehistoryTopPos:0,showhideplaylistRightPos:0,smallButtonDistance:4,playVerticalPadding:10,playHorizontalPadding:16,facebookTopPos:0,facebookRightPos:0,twitterTopPos:0,twitterRightPos:0,
 origParentFloat:"",origParentPaddingTop:"",origParentPaddingRight:"",origParentPaddingBottom:"",origParentPaddingLeft:"",windowWidth:0,audioID:"",audioObj:"",radioReaderAjaxInterval:"",totalRadioStationsNo:0,ajaxReturnedRadioStationsNo:0,lastfm:"",isFlashNeeded:!0,myFlashObject:"",rndNum:0,prevVolumeVal:1,myregexp:/^(http|https):\/\/(.*):(.*)\/(.*)$/,myregexp_radiojar:/^(http|https):\/\/(.*)\/(.*)$/,http_or_https:"http",ip:"",port:"",mount_point:"",now_playing_current_k:-1,now_playing_found:!1,now_playing_arr_lenght:0,
 now_playing_arr:["stats?sid=1","7.html","status-json.xsl","status.xsl"],history_current_k:0,history_arr:["played.html"],the_artist_id:"",the_wikidata_id:"",musicbrainz_setTimeout:"",no_artist_image_setTimeout:"",the_artist_id_history_arr:[""],the_wikidata_id_history_arr:[""],musicbrainzHistory_setTimeout_arr:[""],wiki_photo_path:a.noImageAvailable};a.iceCastFirst&&(d.now_playing_current_k=1,d.isHistoryGenerated=!0);a.preserveOriginalUpperLowerCase||(v.css({"text-transform":"uppercase"}),y.css({"text-transform":"capitalize"}));
 a.sticky||(a.startMinified=!1);30>a.nowPlayingInterval&&(a.nowPlayingInterval=44);a.showOnlyPlayButton&&(a.startMinified=!1,a.showFacebookBut=!1,a.showVolume=!1,a.showTwitterBut=!1,a.showRadioStation=!1,a.showTitle=!1,a.showHistoryBut=!1,a.showHistory=!1,a.playerWidth=n.width()+2*d.playHorizontalPadding,a.historyPadding=0);a.origWidth=a.playerWidth;d.temp_showHistoryBut=a.showHistoryBut;d.now_playing_arr_lenght=Object.keys(d.now_playing_arr).length;d.audioID=b.attr("id");-1==(-1==navigator.userAgent.indexOf("Opera")&&
 navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&(a.autoPlay=!1),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&-1==navigator.platform.indexOf("Win")&&(a.autoPlay=!1));d.isFlashNeeded=aa(d);-1!=z&&(d.isFlashNeeded=!0);d.isFlashNeeded=!1;a.showFacebookBut&&(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,version:"v3.2",status:!0,cookie:!0,xfbml:!0})},function(a,b,c){var d=a.getElementsByTagName(b)[0];
 a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//connect.facebook.com/en_US/sdk.js",d.parentNode.insertBefore(a,d))}(document,"script","facebook-jssdk"),w.on("click",function(){FB.ui({method:"share_open_graph",action_type:"og.likes",action_properties:JSON.stringify({object:{"og:url":document.URL,"og:title":a.facebookShareTitle,"og:description":a.facebookShareDescription,"og:image":a.facebookShareImage}})},function(a){})}));if(a.showTwitterBut)r.on("click",function(){window.open("https://twitter.com/intent/tweet?url="+
 document.URL+"&text="+a.radio_name,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")});S("block",d,a,e,H,x,D,F,n,y,A,v,h,b,C,B,k,l,g,m,t,u,q,p,r,w);d.audioPlayerHeight=C.height()+l.height()+m.height();a.showOnlyPlayButton&&(d.audioPlayerHeight=n.height()+2*d.playVerticalPadding);e.height(d.audioPlayerHeight);if(a.startMinified||a.showOnlyPlayButton)d.historyInitialHeight=0;d.wrapperHeight=d.audioPlayerHeight+d.historyInitialHeight+a.historyTopPos;a.showHistory&&
 a.showHistoryOnInit||(d.wrapperHeight=d.audioPlayerHeight);B.css({border:a.playerBorderSize+"px solid "+a.playerBorderColor,width:e.width()+"px",height:d.wrapperHeight+"px"});a.centerPlayer&&B.css({margin:"0 auto"});var x=c(".thumbsHolderWrapper",e),F=c(".historyPadding",e),D=c(".thumbsHolderVisibleWrapper",e),H=c(".thumbsHolder",e);d.audio6_html5_sliderVertical=c(".slider-vertical",e);F.css({padding:a.historyPadding+"px"});D.append('<div class="readingData">'+a.translateReadingData+"</div>");k.width(a.playerWidth-
 2*a.historyPadding);k.html(a.historyTranslate);k.css({color:a.historyTitleColor});a.showHistory||x.css({opacity:0});a.showHistoryOnInit||x.css({opacity:0,"margin-top":"-20px"});x.css({width:e.width()+"px",top:d.audioPlayerHeight+a.historyTopPos+"px",left:"0px",background:a.historyBgColor});D.width(e.width());a.sticky&&(B.addClass("audio6_html5_sticky_div"),t.on("click",function(){var c=500;if(d.isMinified){d.isMinified=!1;t.removeClass("AudioOpenBut");var f="block";d.temp_showHistoryBut=a.showHistoryBut;
 d.audioPlayerHeight=parseInt(a.playerWidth/a.origWidth*a.imageHeight,10)+l.height()+m.height();var z=0>x.css("margin-top").substring(0,x.css("margin-top").length-2)?d.audioPlayerHeight:d.audioPlayerHeight+x.height()+a.historyTopPos}else d.isMinified=!0,t.addClass("AudioOpenBut"),f="none",d.audioPlayerHeight=l.height()+m.height(),z=d.audioPlayerHeight,d.temp_showHistoryBut=!1;S(f,d,a,e,H,x,D,F,n,y,A,v,h,b,C,B,k,l,g,m,t,u,q,p,r,w);C.css({display:f});a.startMinified?(c=0,a.startMinified=!1):c=500;x.css({display:f,
 top:d.audioPlayerHeight+a.historyTopPos+"px"});d.gen_total_images>a.numberOfThumbsPerScreen&&d.audio6_html5_sliderVertical.css({display:f,top:d.audioPlayerHeight+a.historyTopPos+2*a.historyPadding+2+k.height()+"px"});B.animate({height:z},c,"easeOutQuad",function(){})}));q.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(b,c){a.initialVolume=c.value;d.isFlashNeeded?d.myFlashObject.myAS3function(J(d,a,H,e),a.initialVolume):document.getElementById(d.audioID).volume=
 c.value},stop:function(a,b){}});document.getElementById(d.audioID).volume=a.initialVolume;q.css({background:a.volumeOffColor});c(".ui-slider-range",q).css({background:a.volumeOnColor});n.on("click",function(){var b=d.isFlashNeeded?!n.hasClass("AudioPause"):document.getElementById(d.audioID).paused;Z();0==b?(d.isFlashNeeded?d.myFlashObject.myAS3function("_pause_radio_stream_",a.initialVolume):document.getElementById(d.audioID).pause(),n.removeClass("AudioPause")):(d.isFlashNeeded?d.myFlashObject.myAS3function("_play_radio_stream_",
 a.initialVolume):(document.getElementById(d.audioID).src=J(d,a,H,e),document.getElementById(d.audioID).load(),document.getElementById(d.audioID).play()),n.addClass("AudioPause"))});u.on("click",function(){if(0>x.css("margin-top").substring(0,x.css("margin-top").length-2)){var b=1;var c="block";var e="0px";var f=d.audioPlayerHeight+x.height()+a.historyTopPos;x.css({display:c});d.gen_total_images>a.numberOfThumbsPerScreen&&d.audio6_html5_sliderVertical.css({opacity:1,display:"block"})}else b=0,c="none",
 e="-20px",d.gen_total_images>a.numberOfThumbsPerScreen&&d.audio6_html5_sliderVertical.css({opacity:0,display:"none"}),f=d.audioPlayerHeight;x.css({"z-index":-1});x.animate({opacity:b,"margin-top":e},500,"easeOutQuad",function(){x.css({display:c,"z-index":"auto"})});B.animate({height:f},500,"easeOutQuad",function(){})});p.on("click",function(){document.getElementById(d.audioID).muted?(document.getElementById(d.audioID).muted=!1,p.removeClass("VolumeButtonMuted"),d.isFlashNeeded&&(a.initialVolume=d.prevVolumeVal,
 d.myFlashObject.myAS3function(J(d,a,H,e),a.initialVolume))):(document.getElementById(d.audioID).muted=!0,p.addClass("VolumeButtonMuted"),d.isFlashNeeded&&(d.prevVolumeVal=a.initialVolume,a.initialVolume=0,d.myFlashObject.myAS3function(J(d,a,H,e),a.initialVolume)))});x.swipe({swipeStatus:function(b,e,f,g,h,k){"up"!=f&&"down"!=f||0==g||(currentScrollVal=d.audio6_html5_sliderVertical.slider("value"),currentScrollVal="up"==f?currentScrollVal-1.5:currentScrollVal+1.5,d.audio6_html5_sliderVertical.slider("value",
 currentScrollVal),c("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()}),M(currentScrollVal,d,a,H))},threshold:100,maxTimeThreshold:500,fingers:"all",allowPageScroll:"none",preventDefaultEvents:!1});d.isFlashNeeded&&(d.rndNum=parseInt(998999*Math.random()+1E3),e.append("<div id='swfHolder"+d.rndNum+"'></div>"),swfobject.addDomLoadEvent(function(){d.myFlashObject=swfobject.createSWF({data:a.pathToAjaxFiles+"flash_player.swf",width:"0",height:"0"},{flashvars:"streamUrl="+
 a.radio_stream+"&autoPlay="+a.autoPlay+"&initialVolume="+a.initialVolume},"swfHolder"+d.rndNum)}),a.autoPlay&&n.addClass("AudioPause"));Y(d,a,H,e,n,y,A,v,h,b,C,D,x,F,B,k,t);-1==I.indexOf("ipad")&&-1==I.indexOf("iphone")&&-1==I.indexOf("ipod")&&-1==I.indexOf("webos")||n.removeClass("AudioPause");var E=function(){""==d.origParentFloat&&(d.origParentFloat=e.parent().css("float"),d.origParentPaddingTop=e.parent().css("padding-top"),d.origParentPaddingRight=e.parent().css("padding-right"),d.origParentPaddingBottom=
 e.parent().css("padding-bottom"),d.origParentPaddingLeft=e.parent().css("padding-left"));a.playerWidth!=a.origWidth||a.playerWidth>c(window).width()?e.parent().css({"float":"none","padding-top":0,"padding-right":0,"padding-bottom":0,"padding-left":0}):e.parent().css({"float":d.origParentFloat,"padding-top":d.origParentPaddingTop,"padding-right":d.origParentPaddingRight,"padding-bottom":d.origParentPaddingBottom,"padding-left":d.origParentPaddingLeft});var f=e.parent().parent().width();if(e.width()!=
 f){a.playerWidth=a.origWidth>f?f:a.origWidth;if(e.width()!=a.playerWidth){S("block",d,a,e,H,x,D,F,n,y,A,v,h,b,C,B,k,l,g,m,t,u,q,p,r,w);d.audioPlayerHeight=C.height()+l.height()+m.height();d.isMinified&&(d.audioPlayerHeight=l.height()+m.height());e.height(d.audioPlayerHeight);d.wrapperHeight=d.audioPlayerHeight+x.height()+a.historyTopPos;if(!a.showHistory||!a.showHistoryOnInit||d.isMinified||0>x.css("margin-top").substring(0,x.css("margin-top").length-2))d.wrapperHeight=d.audioPlayerHeight;B.css({width:e.width()+
 "px",height:d.wrapperHeight+"px"});k.width(a.playerWidth-2*a.historyPadding);x.css({width:e.width()+"px",top:d.audioPlayerHeight+a.historyTopPos+"px"});D.width(e.width());K(d,a,e,H,x,D,F,n,y,A,v,h,b,C,B,k)}a.playerWidth<c(window).width()&&e.parent().css({"float":d.origParentFloat,"padding-top":d.origParentPaddingTop,"padding-right":d.origParentPaddingRight,"padding-bottom":d.origParentPaddingBottom,"padding-left":d.origParentPaddingLeft})}},G=!1;c(window).on("resize",function(){var b=!0;-1!=z&&9==
 z&&0==d.windowWidth&&(b=!1);d.windowWidth==c(window).width()?(b=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,b=!0)):d.windowWidth=c(window).width();a.responsive&&b&&(!1!==G&&clearTimeout(G),G=setTimeout(function(){E()},300))});a.responsive&&E()})};c.fn.audio6_html5.defaults={radio_stream:"http://194.232.200.150:80/;",radio_name:"Idobi Anthm",url_custom_metdata_file:"",metadata_file_type:"",playerWidth:335,imageHeight:335,
 skin:"whiteControllers",initialVolume:1,autoPlay:!0,loop:!0,playerBg:"#000000",volumeOffColor:"#454545",volumeOnColor:"#ffffff",timerColor:"#ffffff",songTitleColor:"#ffffff",authorTitleColor:"#ffffff",lineSeparatorColor:"#636363",radioStationColor:"#ffffff",frameBehindTextColor:"#000000",frameBehindButtonsColor:"#454545",playerBorderSize:0,playerBorderColor:"#000000",sticky:!1,startMinified:!1,showOnlyPlayButton:!1,centerPlayer:!1,iceCastFirst:!1,showFacebookBut:!0,facebookAppID:"",facebookShareTitle:"HTML5 Radio Player With History - Shoutcast and Icecast",
 facebookShareDescription:"A top-notch responsive HTML5 Radio Player compatible with all major browsers and mobile devices.",facebookShareImage:"",showVolume:!0,showTwitterBut:!0,showRadioStation:!0,showTitle:!0,showHistoryBut:!0,showHistory:!0,showHistoryOnInit:!0,translateReadingData:"reading history...",historyTranslate:"HISTORY - latest played songs",historyTitleColor:"#858585",historyTopPos:0,historyBgColor:"#ebebeb",historyRecordBgColor:"transparent",historyRecordBottomBorderColor:"transparent",
 historyRecordSongColor:"#000000",historyRecordSongBottomBorderColor:"#d0d0d0",historyRecordAuthorColor:"#6d6d6d",numberOfThumbsPerScreen:3,historyPadding:16,preserveOriginalUpperLowerCase:!1,responsive:!0,historyRecordTitleLimit:25,historyRecordAuthorLimit:36,nowPlayingInterval:35,grabLastFmPhoto:!0,optional_images_path:"",azuracast_api_nowplaying_url:"",azuracast_get_image:!1,pathToAjaxFiles:"",noImageAvailable:"noimageavailable.jpg",lastFMApiKey:"",lastFMSecret:"",origWidth:0,isSliderInitialized:!1,
 isProgressInitialized:!1,isPlaylistSliderInitialized:!1}})(jQuery);
