/*
 * Hero - Shoutcast and Icecast Radio Player With History - v4.0
 * Copyright 2017-2020, LambertGroup
 *
 */

 (function(g){function N(a,b,d,e){g(a.thumbsHolder_Thumbs[a.current_img_no]).css({background:b.playlistRecordBgOnColor,"border-bottom-color":b.playlistRecordBottomBorderOnColor,color:b.playlistRecordTextOnColor});a.is_very_first||R(-1,a,b,d);if(""!=b.radio_stream)var q=b.radio_stream;return q}function Y(a){var b=new XMLHttpRequest;b.open("HEAD",a,!1);b.send();console.log(a+"   ----   "+b.status);return 404!=b.status}function Z(a,b,d,e){var q=b.noImageAvailable,m="",w="";if(""!=a&&void 0!=a){m=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];
 if("jpg"==m||"jpeg"==m||"JPG"==m||"JPEG"==m)w="&iiurlparam=qlow-1000px";g.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+w,{},function(n){""!=g("ii",n).attr("thumburl")&&void 0!=g("ii",n).attr("thumburl")?(q=g("ii",n).attr("thumburl"),d.wiki_photo_path=q):""!=g("ii",n).attr("url")&&void 0!=g("ii",n).attr("url")&&(q=g("ii",n).attr("url"),d.wiki_photo_path=q);Q(b,d,e,q)})}}function T(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B,l,f){var p=
 d.noImageAvailable,h="",y="";if(""!=d.optional_images_path)b.playlist_images_arr[f]=a;else if(""!=a&&void 0!=a){h=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];if("jpg"==h||"jpeg"==h||"JPG"==h||"JPEGs"==h)y="&iiurlparam=qlow-200px";g.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+y,{},function(A){""!=g("ii",A).attr("thumburl")&&void 0!=g("ii",A).attr("thumburl")?p=g("ii",A).attr("thumburl"):""!=g("ii",A).attr("url")&&void 0!=g("ii",
 A).attr("url")&&(p=g("ii",A).attr("url"));b.playlist_images_arr[f]=p})}0!==(f+1)%3&&f!=b.playlist_arr.length-1||setTimeout(function(){O(b,d,e,q,m,w,n,t,x,r,u,v,C,z,B,l)},1E3)}function S(a){var b;a=a.split("");a.forEach(function(d,e){b="\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00df\u00d2\u00d3\u00d4\u00d5\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00f0\u00c7\u00e7\u00d0\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00d1\u00f1\u0160\u0161\u0178\u00ff\u00fd\u017d\u017e\u2019".indexOf(d);
 -1!=b&&(a[e]="AAAAAAaaaaaaBOOOOOOOooooooEEEEeeeeeCcDIIIIiiiiUUUUuuuuNnSsYyyZz'"[b])});return a.join("").trim()}function L(a,b){var d=new XMLHttpRequest;d.open(a.method,"https://zet.pluginsandthemes.ro/"+a.url);d.onload=d.onerror=function(){b(a.method+" "+a.url+"\n"+d.status+" "+d.statusText+"\n\n"+(d.responseText||""))};/^POST/i.test(a.method)&&(d.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),d.setRequestHeader("X-Requested-With","XMLHttpRequest"));d.send(a.data)}function U(a,
 b,d,e,q,m,w,n,t,x,r,u,v,C,z,B){""!=a.curTitle&&a.isHistoryGenerated&&a.prevTitle!=a.curTitle&&(""!=a.prevTitle&&(30<=a.gen_total_images&&(a.gen_total_images--,a.playlist_arr.pop(),a.playlist_images_arr.pop()),b.grabLastFmPhoto||b.azuracast_get_image||b.mscp_pro_api_url||(a.prev_song_image=b.noImageAvailable),a.gen_total_images++,a.playlist_arr.unshift(a.prevTitle),a.playlist_images_arr.unshift(a.prev_song_image),O(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B)),a.prevTitle=a.curTitle)}function P(a,b,d,e,q,m,w,
 n,t,x,r,u,v,C,z,B){if(b.showOnlyPlayButton||a.isRadiojar||""!=b.azuracast_api_nowplaying_url)a.isRadiojar&&(L({method:"GET",url:"http://www.radiojar.com/api/stations/"+a.mount_point+"/now_playing/?my_rand="+Math.random()},function(f){var p=f.indexOf("{");if(-1!==p){var h=f.length;f=f.substr(p,h);f=JSON.parse(f);a.curTitle=f.artist+" - "+f.title;a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim();J(a,b,d,m,w,n,t,x,r,u,v)}}),U(a,b,m,d,e,q,C,w,n,t,x,r,u,v,z,B)),""!=b.azuracast_api_nowplaying_url&&
 (L({method:"GET",url:b.azuracast_api_nowplaying_url+"?my_rand="+Math.random()},function(f){var p=f.indexOf("{");if(-1!==p){var h=f.length;f=f.substr(p,h);f=JSON.parse(f);a.curTitle=f.now_playing.song.text;a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim();b.azuracast_get_image&&(a.azuracast_cur_song_image=b.noImageAvailable,""!=f.now_playing.song.art&&(a.azuracast_cur_song_image=f.now_playing.song.art),a.prev_song_image=a.azuracast_cur_song_image);J(a,b,d,m,w,n,t,x,r,u,v)}}),U(a,b,m,d,e,q,C,
 w,n,t,x,r,u,v,z,B));else{if(""!=b.metadata_file_type||""!=b.azuracast_api_nowplaying_url)if(a.now_playing_found=!0,a.now_playing_current_k=b.metadata_file_type-1,""==a.ip||void 0==a.ip)a.ip=1;!1===a.now_playing_found&&a.now_playing_current_k<a.now_playing_arr_lenght&&a.now_playing_current_k++;var l=a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"?my_rand="+Math.random():"");0===a.now_playing_current_k&&(l=
 a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"&my_rand="+Math.random():""));""!=b.url_custom_metdata_file&&(l=b.url_custom_metdata_file);""!=a.ip&&a.now_playing_current_k<a.now_playing_arr_lenght?(L({method:"GET",url:l},function(f){var p="";switch(a.now_playing_current_k){case 0:if(-1!=f.indexOf("<SONGTITLE>")){a.now_playing_found=!0;var h=f.indexOf("<SONGTITLE>")+11;var y=f.indexOf("</SONGTITLE>")-h;p=f.substr(h,
 y);a.curTitle=p;a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim();J(a,b,d,m,w,n,t,x,r,u,v)}else P(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B);break;case 1:h=f.indexOf("<body>")+6;y=f.length;f=f.substr(h,y);f=f.replace("</body></html>","");p=f.split(",");""!=p[6]&&void 0!=p[6]&&"oracle:0"!=p[6]?(a.now_playing_found=!0,p=p[6],a.curTitle=p,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,t,x,r,u,v)):P(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B);break;case 2:h=f.indexOf('{"icestats":');if(-1!==
 h){y=f.length;f=f.substr(h,y);f=JSON.parse(f);h=!1;var A=0;if(f.icestats.source instanceof Array){for(;A<Object.keys(f.icestats.source).length&&!h;)y=f.icestats.source[A].listenurl,0<y.indexOf(a.mount_point)&&(h=!0,A--),A++;h&&""!=f.icestats.source[A].title&&void 0!=f.icestats.source[A].title&&(a.now_playing_found=!0,p=f.icestats.source[A].title,a.curTitle=p,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,t,x,r,u,v))}else""!=f.icestats.source.title&&void 0!=f.icestats.source.title&&
 (a.now_playing_found=!0,p=f.icestats.source.title,a.curTitle=p,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,t,x,r,u,v))}""==p&&(a.now_playing_found=!1,P(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B));break;case 3:""!=a.mount_point&&(h=f.indexOf(a.mount_point));0<h&&(y=f.length,f=f.substr(h,y));y=f.indexOf("Currently playing:");-1==y&&(y=f.indexOf("Current Song:"));0<y&&(a.now_playing_found=!0,h=f.indexOf('<td class="streamstats">',y),h=0<h?h+24:f.indexOf('<td class="streamdata">',y)+
 23,y=f.indexOf("</td>",h),p=f.substr(h,y-h),a.curTitle=p,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,t,x,r,u,v));""==p&&(a.now_playing_found=!1,P(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B));break;default:a.now_playing_found=!0,a.curTitle="Not available...",a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,t,x,r,u,v)}}),U(a,b,m,d,e,q,C,w,n,t,x,r,u,v,z,B)):(curSong="Data not available...",a.curTitle=curSong,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),
 J(a,b,d,m,w,n,t,x,r,u,v))}}function V(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B,l){b.grabLastFmPhoto&&(a.musicbrainzHistory_setTimeout_arr[l]=setTimeout(function(){var f=a.playlist_arr[l].split("-");f[0]=f[0].trim();a.the_artist_id_history_arr[l]="";a.the_wikidata_id_history_arr[l]="";var p=b.noImageAvailable;a.wiki_photo_path=p;clearTimeout(a.musicbrainzHistory_setTimeout_arr[l]);f[0]=f[0].trim();if(""!=b.optional_images_path){var h=b.optional_images_path+a.playlist_arr[l]+".jpg";h=encodeURI(h);h=h.replace("(",
 "%28");h=h.replace(")","%29");h=h.replace("&apos;","%27");h=h.replace("&amp;","%26");Y(h)||(h=b.noImageAvailable);T(h,a,b,e,d,v,u,C,q,m,w,n,t,x,r,z,B,l)}else g.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+f[0],{},function(y){var A="",c,k="";a.the_artist_id_history_arr[l]="";var E=f[0];E=E.toLowerCase();E=S(E);g("artist",y).each(function(){c=g("name",this)[0];0<g("name",this).length&&""==a.the_artist_id_history_arr[l]&&(A=g(c).text(),A=A.toLowerCase(),A=S(A),E.toLowerCase()==A.toLowerCase()&&
 (a.the_artist_id_history_arr[l]=g(this).attr("id")))});""==a.the_artist_id_history_arr[l]&&"ROCK RADIO"!=f[0]&&(a.the_artist_id_history_arr[l]=g(g("artist",y)[0]).attr("id"));""!=a.the_artist_id_history_arr[l]&&void 0!=a.the_artist_id_history_arr[l]&&(a.musicbrainzHistory_setTimeout_arr[l]=setTimeout(function(){a.the_wikidata_id_history_arr[l]="";g.get("https://musicbrainz.org/ws/2/artist/"+a.the_artist_id_history_arr[l]+"?inc=url-rels",{},function(G){g("relation",G).each(function(){"image"==g(this).attr("type")&&
 0<g("target",this).length&&(k=g("target",this).text(),k=k.substr(k.indexOf("File:",10)+5,k.length),T(k,a,b,e,d,v,u,C,q,m,w,n,t,x,r,z,B,l));"wikidata"==g(this).attr("type")&&0<g("target",this).length&&""==k&&(a.the_wikidata_id_history_arr[l]=g("target",this).text(),a.the_wikidata_id_history_arr[l]=a.the_wikidata_id_history_arr[l].substr(a.the_wikidata_id_history_arr[l].indexOf("/Q",10)+1,a.the_wikidata_id_history_arr[l].length),g.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+
 a.the_wikidata_id_history_arr[l]+"&property=P18&format=xml&origin=*",{},function(H){k=g("datavalue",g("mainsnak",H)).attr("value");T(k,a,b,e,d,v,u,C,q,m,w,n,t,x,r,z,B,l)}))});if(""==k||void 0==k)a.playlist_images_arr[l]=p})},3E3*(l+1)))})},3E3*(l+1)))}function ea(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B,l){clearInterval(a.radioReaderAjaxInterval);if(-1!==b.radio_stream.indexOf("radiojar.com")){a.isRadiojar=!0;var f=b.radio_stream.match(a.myregexp_radiojar);null!=f&&(a.http_or_https=f[1],a.ip=f[2],a.mount_point=
 f[3],a.port="")}else-1==b.radio_stream.indexOf("/",9)&&(b.radio_stream+="/;"),"/"==b.radio_stream.charAt(b.radio_stream.length-1)&&(b.radio_stream+=";"),f=b.radio_stream.match(a.myregexp),null!=f&&(a.http_or_https=f[1],a.ip=f[2],a.port=f[3],a.mount_point=f[4],";"==a.mount_point.trim()&&(a.mount_point=""));r.css({width:b.playerWidth+"px",height:b.imageHeight+"px",background:"url("+b.noImageAvailable+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});
 if(!b.showOnlyPlayButton){P(a,b,d,v,u,e,q,m,w,n,t,x,r,C,z,B);a.radioReaderAjaxInterval=setInterval(function(){P(a,b,d,v,u,e,q,m,w,n,t,x,r,C,z,B)},1E3*b.nowPlayingInterval);a.playlist_arr=[];a.playlist_images_arr=[];var p=-1,h,y,A,c=0;a.isRadiojar&&L({method:"GET",url:"http://www.radiojar.com/api/stations/"+a.mount_point+"/tracks/?my_rand="+Math.random()},function(k){h=k.indexOf("[{");if(-1!==h){y=k.length;k=k.substr(h,y);var E=JSON.parse(k);E.reverse()}for(c=0;c<Object.keys(E).length;c++)""!=E[c].track&&
 "Empty Title"!=E[c].track&&(p++,a.playlist_arr[p]=E[c].artist+" - "+E[c].track,a.playlist_images_arr[p]=b.noImageAvailable,V(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B,p));a.playlist_arr.length?O(a,b,e,d,v,u,C,q,m,w,n,t,x,r,z,B):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&l.click()});""!=b.azuracast_api_nowplaying_url&&L({method:"GET",url:b.azuracast_api_nowplaying_url+"?my_rand="+Math.random()},function(k){h=k.indexOf("{");if(-1!==h){y=k.length;k=k.substr(h,y);k=JSON.parse(k);for(c=0;c<Object.keys(k.song_history).length;c++)""!=
 k.song_history[c].song.text&&"Empty Title"!=k.song_history[c].song.text.text&&(p++,a.playlist_arr[p]=k.song_history[c].song.text,a.playlist_images_arr[p]=b.noImageAvailable,b.azuracast_get_image&&""!=k.song_history[c].song.art&&(a.playlist_images_arr[p]=k.song_history[c].song.art),V(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B,p));a.playlist_arr.length?O(a,b,e,d,v,u,C,q,m,w,n,t,x,r,z,B):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&l.click()}});a.isRadiojar||""!=b.azuracast_api_nowplaying_url||b.iceCastFirst||
 L({method:"GET",url:a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.history_arr[a.history_current_k]},function(k){if(-1!=k.indexOf("Current Song"))for(h=k.indexOf("Current Song")+12,y=k.length,k=k.substr(h,y),A=k.split("</td><td>"),A.shift(),k=0;k<A.length;k++)h=A[k].indexOf("</"),-1!=h&&(y=h,A[k]=A[k].substr(0,y),A[k]=A[k].replace(/<\/?[^>]+(>|$)/g,""),""!=A[k]&&"Empty Title"!=A[k]&&(p++,a.playlist_arr[p]=A[k],a.playlist_arr[p]=a.playlist_arr[p].replace(/(\r?\n|\r)/gm," ").trim(),a.playlist_images_arr[p]=
 b.noImageAvailable,V(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B,p)));a.playlist_arr.length?O(a,b,e,d,v,u,C,q,m,w,n,t,x,r,z,B):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&l.click()})}a.isFlashNeeded?""!=a.myFlashObject&&a.myFlashObject.myAS3function(N(a,b,d,e),b.initialVolume):(document.getElementById(a.audioID).src=N(a,b,d,e),document.getElementById(a.audioID).load(),b.autoPlay&&q.click())}function Q(a,b,d,e){d.css({background:"url("+e+") #000000","background-repeat":"no-repeat","background-position":"top center",
 "background-size":"cover"});b.prev_song_image=b.cur_song_image;b.cur_song_image=e}function J(a,b,d,e,q,m,w,n,t,x,r){a.curSongText="";b.showTitle&&null!=a.curTitle&&""!=a.curTitle&&(a.curSongText+=a.curTitle);b.showRadioStation&&null!=b.radio_name&&""!=b.radio_name&&t.html(b.radio_name);var u=a.curTitle.split("-"),v=b.noImageAvailable;u[0]=u[0].trim();3<=u.length&&(u[0]=u[0].trim()+"-"+u[1].trim());if(b.grabLastFmPhoto&&""!=u[0].trim()){var C,z="",B,l="";a.the_artist_id="";a.the_wikidata_id="";v=b.noImageAvailable;
 a.wiki_photo_path=v;clearTimeout(a.musicbrainz_setTimeout);clearTimeout(a.no_artist_image_setTimeout);u[0]=u[0].trim();""!=u[0]&&void 0!=u[0]&&a.prevTitle!=a.curTitle&&(r.css({background:"url("+v+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"}),a.musicbrainz_setTimeout=setTimeout(function(){""!=b.optional_images_path?(l=b.optional_images_path+a.curTitle+".jpg",l=encodeURI(l),l=l.replace("(","%28"),l=l.replace(")","%29"),l=l.replace("&apos;",
 "%27"),l=l.replace("&amp;","%26"),Y(l)||(l=b.noImageAvailable),v=l,Q(b,a,r,v)):g.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+u[0],{},function(f){a.the_artist_id="";C=u[0];C=C.toLowerCase();C=S(C);g("artist",f).each(function(){B=g("name",this)[0];0<g("name",this).length&&""==a.the_artist_id&&(z=g(B).text(),z=z.toLowerCase(),z=S(z),C.toLowerCase()==z.toLowerCase()&&(a.the_artist_id=g(this).attr("id")))});""==a.the_artist_id&&"ROCK RADIO"!=u[0]&&(a.the_artist_id=g(g("artist",f)[0]).attr("id"));
 ""!=a.the_artist_id&&void 0!=a.the_artist_id&&(a.musicbrainz_setTimeout=setTimeout(function(){a.the_wikidata_id="";g.get("https://musicbrainz.org/ws/2/artist/"+a.the_artist_id+"?inc=url-rels",{},function(p){g("relation",p).each(function(){"image"==g(this).attr("type")&&0<g("target",this).length&&(l=g("target",this).text(),l=l.substr(l.indexOf("File:",10)+5,l.length),Z(l,b,a,r));"wikidata"==g(this).attr("type")&&0<g("target",this).length&&""==l&&(a.the_wikidata_id=g("target",this).text(),a.the_wikidata_id=
 a.the_wikidata_id.substr(a.the_wikidata_id.indexOf("/Q",10)+1,a.the_wikidata_id.length),g.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+a.the_wikidata_id+"&property=P18&format=xml&origin=*",{},function(h){l=g("datavalue",g("mainsnak",h)).attr("value");Z(l,b,a,r)}))});a.no_artist_image_setTimeout=setTimeout(function(){""!=l&&void 0!=l||Q(b,a,r,v)},1E3)})},1500))})},1500))}else b.azuracast_get_image&&(v=a.azuracast_cur_song_image,Q(b,a,r,v)),""!=b.mscp_pro_api_url&&a.prevTitle!=
 a.curTitle&&L({method:"GET",url:b.mscp_pro_api_url},function(f){var p=f.indexOf('{"mscp":'),h=f.length;-1!==p&&(f=f.substr(p,h),f=JSON.parse(f),""!=f.mscp.info[0].cover&&-1==f.mscp.info[0].cover.indexOf("nocover.png")&&(v=f.mscp.info[0].cover.replace(/(\s)/g,"%20"),v=f.mscp.info[0].cover.replace(/100x100/g,"400x400")),Q(b,a,r,v))});a.curSongText&&(d=a.curSongText.split("-"),a.curSongAuthorText=d[0].trim(),2<=d.length&&(a.curSongText=d[1].trim()),3<=d.length&&(a.curSongAuthorText=d[0].trim()+"-"+d[1].trim(),
 a.curSongText=d[2].trim()),m.html(aa(a.curSongAuthorText,b)),n.css({width:"auto"}),a.isStationTitleInsideScrolling=!1,a.stationTitleInsideWait=0,n.stop(),n.css({"margin-left":0}),n.html(a.curSongText),clearInterval(a.timeupdateInterval),n.width()>a.titleWidth?a.timeupdateInterval=setInterval(function(){!a.isStationTitleInsideScrolling&&5<=a.stationTitleInsideWait&&n.width()>a.titleWidth?(a.isStationTitleInsideScrolling=!0,a.stationTitleInsideWait=0,n.html(a.curSongText+" **** "+a.curSongText+" **** "+
 a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),n.css({"margin-left":0}),n.stop().animate({"margin-left":b.playerWidth-n.width()+"px"},parseInt(1E4*(n.width()-b.playerWidth)/150,10),"linear",function(){a.isStationTitleInsideScrolling=!1})):!a.isStationTitleInsideScrolling&&n.width()>a.titleWidth&&a.stationTitleInsideWait++},300):n.css({width:"100%"}))}function R(a,b,d,e){if(b.gen_total_images>d.numberOfThumbsPerScreen){var q=(b.thumbsHolder_ThumbHeight+1)*(b.gen_total_images-
 d.numberOfThumbsPerScreen),m=0;e.stop(!0,!0);g("html, body").off("touchstart touchmove").on("touchstart touchmove",function(w){w.preventDefault()});-1==a||b.isCarouselScrolling?!b.isCarouselScrolling&&b.gen_total_images>d.numberOfThumbsPerScreen&&(b.isCarouselScrolling=!0,m=-1*parseInt((b.thumbsHolder_ThumbHeight+1)*b.current_img_no,10),Math.abs(m)>q&&(m=-1*q),b.gen_total_images>d.numberOfThumbsPerScreen&&d.showPlaylist&&b.audio6_html5_sliderVertical.slider("value",100+parseInt(100*m/q)),e.animate({top:m+
 "px"},500,"easeOutCubic",function(){b.isCarouselScrolling=!1;g("html, body").off("touchstart touchmove").on("touchstart touchmove",function(w){})})):(b.isCarouselScrolling=!0,m=2>=a?-1*q:parseInt(q*(a-100)/100,10),0<m&&(m=0),e.animate({top:m+"px"},1100,"easeOutQuad",function(){b.isCarouselScrolling=!1;g("html, body").off("touchstart touchmove").on("touchstart touchmove",function(w){})}))}}function W(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B,l,f,p,h,y,A,c,k,E,G){e.width(d.playerWidth);if(d.showOnlyPlayButton||
 b.isMinified)a="none";"none"==a?z.css({width:"0px",height:"0px"}):z.css({width:d.playerWidth+"px",height:parseInt(d.playerWidth/d.origWidth*d.imageHeight,10)+"px"});d.sticky&&d.startMinified?z.css({display:"none",top:"0px",left:"0px"}):z.css({display:a,top:"0px",left:"0px"});b.imageTopPos=0;b.imageLeftPos=0;b.frameBehindTextTopPos=z.height();b.frameBehindTextLeftPos=0;d.showOnlyPlayButton?f.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:d.frameBehindTextColor,
 width:0,height:0}):f.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:d.frameBehindTextColor,height:t.height()+2*b.playVerticalPadding+"px"});b.playTopPos=b.frameBehindTextTopPos+b.playVerticalPadding;b.playLeftPos=b.frameBehindTextLeftPos+b.playHorizontalPadding;t.css({top:b.playTopPos+"px",left:b.playLeftPos+"px"});b.titleWidth=d.playerWidth-4*b.playHorizontalPadding-t.width();b.titleTopPos=b.playTopPos+3;b.titleLeftPos=t.width()+2*b.playHorizontalPadding;r.css({color:d.songTitleColor,
 top:b.titleTopPos+"px",left:b.titleLeftPos+"px",width:b.titleWidth+"px"});b.lineSeparatorTopPos=b.titleTopPos+r.height()+2;b.lineSeparatorLeftPos=b.titleLeftPos;p.css({background:d.lineSeparatorColor,top:b.lineSeparatorTopPos+"px",left:b.lineSeparatorLeftPos+"px",width:b.titleWidth+"px"});b.authorTopPos=b.lineSeparatorTopPos+8;b.authorLeftPos=b.titleLeftPos;x.css({color:d.authorTitleColor,top:b.authorTopPos+"px",left:b.authorLeftPos+"px",width:b.titleWidth+"px"});b.minimizeTopPos=b.playTopPos;!d.sticky||
 d.showOnlyPlayButton?(b.minimizeRightPos=0,y.css({display:"none",padding:0,margin:0})):d.sticky&&(b.minimizeRightPos=b.smallButtonDistance,y.css({top:b.minimizeTopPos+"px",right:b.minimizeRightPos+"px"}));b.frameBehindButtonsTopPos=b.frameBehindTextTopPos+f.height();b.frameBehindButtonsLeftPos=0;d.showOnlyPlayButton?h.css({background:d.frameBehindButtonsColor,height:0,top:b.frameBehindButtonsTopPos+"px",left:b.frameBehindButtonsLeftPos+"px"}):h.css({background:d.frameBehindButtonsColor,top:b.frameBehindButtonsTopPos+
 "px",left:b.frameBehindButtonsLeftPos+"px"});b.radioStationTopPos=b.frameBehindButtonsTopPos+Math.floor(h.height()-v.height())/2;b.radioStationLeftPos=b.playHorizontalPadding;v.css({color:d.radioStationColor,top:b.radioStationTopPos+"px",left:b.radioStationLeftPos+"px",width:b.titleWidth+"px"});0==b.historyButWidth&&(b.historyButWidth=A.width());b.showhidehistoryTopPos=b.frameBehindButtonsTopPos+Math.floor((h.height()-A.height())/2);b.temp_showHistoryBut?(b.showhideplaylistRightPos=2*b.smallButtonDistance,
 A.css({display:"block",width:b.historyButWidth+"px",top:b.showhidehistoryTopPos+"px",right:b.showhideplaylistRightPos+"px"})):(b.showhideplaylistRightPos=0,A.css({display:"none",width:0,padding:0,margin:0}));c.css({display:"none",width:0,padding:0,margin:0});b.volumeTopPos=b.frameBehindButtonsTopPos+Math.floor((h.height()-k.height())/2);d.showVolume?(b.volumeRightPos=b.showhideplaylistRightPos+A.width()+b.smallButtonDistance,k.css({top:b.volumeTopPos+"px",right:b.volumeRightPos+"px"})):(b.volumeRightPos=
 b.showhideplaylistRightPos+A.width(),k.css({display:"none",width:0,padding:0,margin:0}));b.twitterTopPos=b.frameBehindButtonsTopPos+Math.floor((h.height()-E.height())/2);d.showTwitterBut?(b.twitterRightPos=b.volumeRightPos+k.width()+b.smallButtonDistance,E.css({top:b.twitterTopPos+"px",right:b.twitterRightPos+"px"})):(b.twitterRightPos=b.volumeRightPos+k.width(),E.css({display:"none",width:0,padding:0,margin:0}));b.facebookTopPos=b.frameBehindButtonsTopPos+Math.floor((h.height()-G.height())/2);d.showFacebookBut?
 (b.facebookRightPos=b.twitterRightPos+E.width()+b.smallButtonDistance,G.css({top:b.facebookTopPos+"px",right:b.facebookRightPos+"px"})):(b.facebookRightPos=b.twitterRightPos,G.css({display:"none",width:0,padding:0,margin:0}))}function O(a,b,d,e,q,m,w,n,t,x,r,u,v,C,z,B){if(!b.showOnlyPlayButton){e.stop(!0,!0);a.isCarouselScrolling=!1;g(".readingData",m).css({display:"none"});n=parseInt(b.playerWidth/b.origWidth*b.historyRecordTitleLimit,10);t=parseInt(b.playerWidth/b.origWidth*b.historyRecordAuthorLimit,
 10);x=[];a.isHistoryGenerated=!0;e.html("");for(r=a.gen_total_images=0;r<a.playlist_arr.length;r++)a.gen_total_images++,x=a.playlist_arr[r].split("-"),1>x.length?a.gen_total_images--:(a.thumbsHolder_Thumb=g('<div class="thumbsHolder_ThumbOFF" rel="'+(a.gen_total_images-1)+'" data-origID="'+r+'"><div class="padding"><div class="img_div" style="background-image:url('+a.playlist_images_arr[r]+');background-color:#000000;"></div><span class="titlex">'+ba(x[1],n,b)+'</span><span class="authorx">'+ba(x[0],
 t,b)+"</span></div></div>"),e.append(a.thumbsHolder_Thumb),0==a.thumbsHolder_ThumbHeight&&(a.thumbsHolder_ThumbHeight=a.thumbsHolder_Thumb.height()),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_ThumbHeight+1)*a.gen_total_images+"px",background:b.historyRecordBgColor,"border-bottom-color":b.historyRecordBottomBorderColor,color:b.historyRecordTextColor}),g(".titlex",a.thumbsHolder_Thumb).css({color:b.historyRecordSongColor,"border-bottom-color":b.historyRecordSongBottomBorderColor}),g(".authorx",a.thumbsHolder_Thumb).css({color:b.historyRecordAuthorColor}),
 a.current_img_no=0);q.height(2*b.historyPadding+(a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen+B.height()+b.historyPadding);m.height((a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen);m.css({"margin-top":B.height()+b.historyPadding+"px"});w.css({padding:b.historyPadding+"px"});a.thumbsHolder_Thumbs=g(".thumbsHolder_ThumbOFF",d);a.wrapperHeight=a.audioPlayerHeight+q.height()+b.historyTopPos;if(!b.showHistory||!b.showHistoryOnInit||0>q.css("margin-top").substring(0,q.css("margin-top").length-
 2))a.wrapperHeight=a.audioPlayerHeight;a.isMinified||z.css({height:a.wrapperHeight+"px"});a.gen_total_images>b.numberOfThumbsPerScreen&&b.showHistory?(b.isPlaylistSliderInitialized&&a.audio6_html5_sliderVertical.slider("destroy"),a.audio6_html5_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(l,f){R(f.value,a,b,e)}}),b.isPlaylistSliderInitialized=!0,a.audio6_html5_sliderVertical.css({display:"inline",position:"absolute",height:q.height()-20-3*
 b.historyPadding-B.height()+"px",left:d.width()-a.audio6_html5_sliderVertical.width()-b.historyPadding+"px",top:a.audioPlayerHeight+b.historyTopPos+2*b.historyPadding+2+B.height()+"px"}),b.showHistoryOnInit||a.audio6_html5_sliderVertical.css({opacity:0,display:"none"}),g(".thumbsHolder_ThumbOFF",d).css({width:d.width()-a.audio6_html5_sliderVertical.width()-2*b.historyPadding-3+"px"})):(b.isPlaylistSliderInitialized&&(a.audio6_html5_sliderVertical.slider("destroy"),b.isPlaylistSliderInitialized=!1),
 g(".thumbsHolder_ThumbOFF",d).css({width:d.width()-2*b.historyPadding+"px"}));m.mousewheel(function(l,f,p,h){a.gen_total_images>b.numberOfThumbsPerScreen&&(l.preventDefault(),l=a.audio6_html5_sliderVertical.slider("value"),1<parseInt(l)&&-1==parseInt(f)||100>parseInt(l)&&1==parseInt(f))&&(l+=3*f,a.audio6_html5_sliderVertical.slider("value",l),R(l,a,b,e))});e.css({top:"0px"})}}function aa(a,b){b.preserveOriginalUpperLowerCase||(a=a.toLowerCase(),a=a.replace(/\b[a-z]/g,function(d){return d.toUpperCase()}),
 a=a.replace(/&Apos;/gi,"'"),a=a.replace(/&Amp;/gi,"&"),a=a.replace(/'[A-Z]/g,function(d){return d.toLowerCase()}));return a}function ba(a,b,d){a=String(a);var e="";if(a.length>b){a=a.substring(0,b);var q=a.split(" ");a=a.substring(b-2,b-1);""!=a&&(q.pop(),e="...");a=q.join(" ")}a=aa(a,d);return a+e}function fa(){g("audio").each(function(){g(".AudioPlay").removeClass("AudioPause");g(this)[0].pause()})}function ca(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,
 d=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=d.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,d=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=d.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function ha(a){var b=!1;document.getElementById(a.audioID).canPlayType&&"no"!=document.getElementById(a.audioID).canPlayType("audio/mpeg")&&""!=document.getElementById(a.audioID).canPlayType("audio/mpeg")||(b=!0);return b}var K=navigator.userAgent.toLowerCase();g.fn.audio6_html5=
 function(a){a=g.extend({},g.fn.audio6_html5.defaults,a);ca();return this.each(function(){var b=g(this),d=g('<div class="frameBehindText"></div><div class="frameBehindButtons"></div> <div class="ximage"></div> <div class="AudioControls"> <a class="AudioCloseBut" title="Minimize"></a><a class="AudioFacebook" title="Facebook"></a><a class="AudioTwitter" title="Twitter"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div>   </div>   <div class="songTitle"><div class="songTitleInside"></div></div>  <div class="songAuthorLineSeparator"></div>  <div class="songAuthor"></div>  <div class="radioStation"></div>     <div class="thumbsHolderWrapper"><div class="historyPadding">  <div class="historyTitle"></div> <div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div></div>  <div class="slider-vertical"></div>'),
 e=b.parent(".audio6_html5");e.addClass(a.skin);e.append(d);var q=g(".frameBehindText",e),m=g(".frameBehindButtons",e);g(".AudioControls",e);var w=g(".AudioFacebook",e),n=g(".AudioTwitter",e),t=g(".AudioPlay",e),x=g(".AudioShowHidePlaylist",e),r=g(".VolumeButton",e),u=g(".VolumeSlider",e),v=g(".AudioCloseBut",e),C=g(".songTitle",e),z=g(".songTitleInside",e),B=g(".songAuthor",e),l=g(".songAuthorLineSeparator",e),f=g(".radioStation",e),p=g(".ximage",e),h=g(".historyTitle",e);e.wrap("<div class='the_wrapper'></div>");
 var y=e.parent(),A=ca();if(-1!=K.indexOf("ipad")||-1!=K.indexOf("iphone")||-1!=K.indexOf("ipod")||-1!=K.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))a.autoPlay=!1;e.css({background:"transparent"});d=Math.floor(1E5*Math.random());var c={current_img_no:0,origID:0,is_very_first:!0,total_images:0,gen_total_images:0,is_changeSrc:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",playlist_images_arr:"",isCarouselScrolling:!1,isHistoryGenerated:!1,isStationTitleInsideScrolling:!1,curTitle:"",
 prevTitle:"",cur_song_image:"",prev_song_image:"",azuracast_cur_song_image:a.noImageAvailable,curSongText:"",curSongAuthorText:"",stationTitleInsideWait:0,audioPlayerWidth:0,audioPlayerHeight:0,wrapperHeight:0,temp_showHistoryBut:!0,historyButWidth:0,isRadiojar:!1,historyInitialHeight:90,thumbsHolder_Thumb:g('<div class="thumbsHolder_ThumbOFF" rel="0"><div class="padding">test</div></div>'),thumbsHolder_ThumbHeight:0,thumbsHolder_Thumbs:"",constantDistance:0,titleWidth:0,radioStationTopPos:0,radioStationLeftPos:0,
 titleTopPos:0,titleLeftPos:0,lineSeparatorTopPos:0,lineSeparatorLeftPos:0,authorTopPos:0,authorLeftPos:0,minimizeTopPos:0,minimizeRightPos:0,isMinified:!1,imageTopPos:0,imageLeftPos:0,frameBehindButtonsTopPos:0,frameBehindButtonsLeftPos:0,frameBehindTextTopPos:0,frameBehindTextLeftPos:0,playTopPos:0,playLeftPos:0,volumeTopPos:0,volumeRightPos:0,volumesliderTopPos:0,volumesliderLeftPos:0,showhidehistoryTopPos:0,showhideplaylistRightPos:0,smallButtonDistance:4,playVerticalPadding:10,playHorizontalPadding:16,
 facebookTopPos:0,facebookRightPos:0,twitterTopPos:0,twitterRightPos:0,origParentFloat:"",origParentPaddingTop:"",origParentPaddingRight:"",origParentPaddingBottom:"",origParentPaddingLeft:"",windowWidth:0,audioObj:"",radioReaderAjaxInterval:"",totalRadioStationsNo:0,ajaxReturnedRadioStationsNo:0,lastfm:"",isFlashNeeded:!0,myFlashObject:"",rndNum:0,prevVolumeVal:1,myregexp:/^(http|https):\/\/(.*):(.*)\/(.*)$/,myregexp_radiojar:/^(http|https):\/\/(.*)\/(.*)$/,http_or_https:"http",ip:"",port:"",mount_point:"",
 now_playing_current_k:-1,now_playing_found:!1,now_playing_arr_lenght:0,now_playing_arr:["stats?sid=1","7.html","status-json.xsl","status.xsl"],history_current_k:0,history_arr:["played.html"],the_artist_id:"",the_wikidata_id:"",musicbrainz_setTimeout:"",no_artist_image_setTimeout:"",the_artist_id_history_arr:[""],the_wikidata_id_history_arr:[""],musicbrainzHistory_setTimeout_arr:[""],wiki_photo_path:a.noImageAvailable,html5_audio_tag:"",audioID:"hero_audio_tag_id_"+d};a.azuracast_get_image&&""!=a.azuracast_api_nowplaying_url&&
 (a.grabLastFmPhoto=!1);""!=a.mscp_pro_api_url&&(a.grabLastFmPhoto=!1);a.iceCastFirst&&(c.now_playing_current_k=1,c.isHistoryGenerated=!0);a.preserveOriginalUpperLowerCase||(z.css({"text-transform":"uppercase"}),B.css({"text-transform":"capitalize"}));a.sticky||(a.startMinified=!1);30>a.nowPlayingInterval&&(a.nowPlayingInterval=44);a.showOnlyPlayButton&&(a.startMinified=!1,a.showFacebookBut=!1,a.showVolume=!1,a.showTwitterBut=!1,a.showRadioStation=!1,a.showTitle=!1,a.showHistoryBut=!1,a.showHistory=
 !1,a.playerWidth=t.width()+2*c.playHorizontalPadding,a.historyPadding=0);a.origWidth=a.playerWidth;c.temp_showHistoryBut=a.showHistoryBut;c.now_playing_arr_lenght=Object.keys(c.now_playing_arr).length;c.html5_audio_tag=g('<audio id="'+c.audioID+'" preload="metadata"></audio>');e.append(c.html5_audio_tag);-1==(-1==navigator.userAgent.indexOf("Opera")&&navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&(a.autoPlay=!1),-1<navigator.userAgent.indexOf("Firefox")&&
 (a.autoPlay=!1),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&-1==navigator.platform.indexOf("Win")&&(a.autoPlay=!1));c.isFlashNeeded=ha(c);-1!=A&&(c.isFlashNeeded=!0);c.isFlashNeeded=!1;a.showFacebookBut&&(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,version:"v3.2",status:!0,cookie:!0,xfbml:!0})},function(D,F,I){var M=D.getElementsByTagName(F)[0];D.getElementById(I)||(D=D.createElement(F),D.id=I,D.src="//connect.facebook.com/en_US/sdk.js",M.parentNode.insertBefore(D,
 M))}(document,"script","facebook-jssdk"),w.on("click",function(){FB.ui({method:"share_open_graph",action_type:"og.likes",action_properties:JSON.stringify({object:{"og:url":document.URL,"og:title":a.facebookShareTitle,"og:description":a.facebookShareDescription,"og:image":a.facebookShareImage}})},function(D){})}));if(a.showTwitterBut)n.on("click",function(){window.open("https://twitter.com/intent/tweet?url="+document.URL+"&text="+a.radio_name,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")});
 W("block",c,a,e,H,k,G,E,t,B,C,z,f,b,p,y,h,q,l,m,v,x,u,r,n,w);c.audioPlayerHeight=p.height()+q.height()+m.height();a.showOnlyPlayButton&&(c.audioPlayerHeight=t.height()+2*c.playVerticalPadding);e.height(c.audioPlayerHeight);if(a.startMinified||a.showOnlyPlayButton)c.historyInitialHeight=0;c.wrapperHeight=c.audioPlayerHeight+c.historyInitialHeight+a.historyTopPos;a.showHistory&&a.showHistoryOnInit||(c.wrapperHeight=c.audioPlayerHeight);y.css({border:a.playerBorderSize+"px solid "+a.playerBorderColor,
 width:e.width()+"px",height:c.wrapperHeight+"px"});a.centerPlayer&&y.css({margin:"0 auto"});var k=g(".thumbsHolderWrapper",e),E=g(".historyPadding",e),G=g(".thumbsHolderVisibleWrapper",e),H=g(".thumbsHolder",e);c.audio6_html5_sliderVertical=g(".slider-vertical",e);E.css({padding:a.historyPadding+"px"});G.append('<div class="readingData">'+a.translateReadingData+"</div>");h.width(a.playerWidth-2*a.historyPadding);h.html(a.historyTranslate);h.css({color:a.historyTitleColor});a.showHistory||k.css({opacity:0});
 a.showHistoryOnInit||k.css({opacity:0,"margin-top":"-20px"});k.css({width:e.width()+"px",top:c.audioPlayerHeight+a.historyTopPos+"px",left:"0px",background:a.historyBgColor});G.width(e.width());a.sticky&&(y.addClass("audio6_html5_sticky_div"),v.on("click",function(){var D=500;if(c.isMinified){c.isMinified=!1;v.removeClass("AudioOpenBut");var F="block";c.temp_showHistoryBut=a.showHistoryBut;c.audioPlayerHeight=parseInt(a.playerWidth/a.origWidth*a.imageHeight,10)+q.height()+m.height();var I=0>k.css("margin-top").substring(0,
 k.css("margin-top").length-2)?c.audioPlayerHeight:c.audioPlayerHeight+k.height()+a.historyTopPos}else c.isMinified=!0,v.addClass("AudioOpenBut"),F="none",c.audioPlayerHeight=q.height()+m.height(),I=c.audioPlayerHeight,c.temp_showHistoryBut=!1;W(F,c,a,e,H,k,G,E,t,B,C,z,f,b,p,y,h,q,l,m,v,x,u,r,n,w);p.css({display:F});a.startMinified?(D=0,a.startMinified=!1):D=500;k.css({display:F,top:c.audioPlayerHeight+a.historyTopPos+"px"});c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({display:F,
 top:c.audioPlayerHeight+a.historyTopPos+2*a.historyPadding+2+h.height()+"px"});y.animate({height:I},D,"easeOutQuad",function(){})}));u.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(D,F){a.initialVolume=F.value;c.isFlashNeeded?c.myFlashObject.myAS3function(N(c,a,H,e),a.initialVolume):document.getElementById(c.audioID).volume=F.value},stop:function(D,F){}});document.getElementById(c.audioID).volume=a.initialVolume;u.css({background:a.volumeOffColor});
 g(".ui-slider-range",u).css({background:a.volumeOnColor});t.on("click",function(){var D=c.isFlashNeeded?!t.hasClass("AudioPause"):document.getElementById(c.audioID).paused;fa();0==D?(c.isFlashNeeded?c.myFlashObject.myAS3function("_pause_radio_stream_",a.initialVolume):document.getElementById(c.audioID).pause(),t.removeClass("AudioPause")):(c.isFlashNeeded?c.myFlashObject.myAS3function("_play_radio_stream_",a.initialVolume):(document.getElementById(c.audioID).src=N(c,a,H,e),document.getElementById(c.audioID).load(),
 document.getElementById(c.audioID).play()),t.addClass("AudioPause"))});x.on("click",function(){if(0>k.css("margin-top").substring(0,k.css("margin-top").length-2)){var D=1;var F="block";var I="0px";var M=c.audioPlayerHeight+k.height()+a.historyTopPos;k.css({display:F});c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({opacity:1,display:"block"})}else D=0,F="none",I="-20px",c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({opacity:0,display:"none"}),
 M=c.audioPlayerHeight;k.css({"z-index":-1});k.animate({opacity:D,"margin-top":I},500,"easeOutQuad",function(){k.css({display:F,"z-index":"auto"})});y.animate({height:M},500,"easeOutQuad",function(){})});r.on("click",function(){document.getElementById(c.audioID).muted?(document.getElementById(c.audioID).muted=!1,r.removeClass("VolumeButtonMuted"),c.isFlashNeeded&&(a.initialVolume=c.prevVolumeVal,c.myFlashObject.myAS3function(N(c,a,H,e),a.initialVolume))):(document.getElementById(c.audioID).muted=!0,
 r.addClass("VolumeButtonMuted"),c.isFlashNeeded&&(c.prevVolumeVal=a.initialVolume,a.initialVolume=0,c.myFlashObject.myAS3function(N(c,a,H,e),a.initialVolume)))});k.swipe({swipeStatus:function(D,F,I,M,ja,ka){"up"!=I&&"down"!=I||0==M||(currentScrollVal=c.audio6_html5_sliderVertical.slider("value"),currentScrollVal="up"==I?currentScrollVal-1.5:currentScrollVal+1.5,c.audio6_html5_sliderVertical.slider("value",currentScrollVal),g("html, body").off("touchstart touchmove").on("touchstart touchmove",function(ia){ia.preventDefault()}),
 R(currentScrollVal,c,a,H))},threshold:100,maxTimeThreshold:500,fingers:"all",allowPageScroll:"none",preventDefaultEvents:!1});c.isFlashNeeded&&(c.rndNum=parseInt(998999*Math.random()+1E3),e.append("<div id='swfHolder"+c.rndNum+"'></div>"),swfobject.addDomLoadEvent(function(){c.myFlashObject=swfobject.createSWF({data:a.pathToAjaxFiles+"flash_player.swf",width:"0",height:"0"},{flashvars:"streamUrl="+a.radio_stream+"&autoPlay="+a.autoPlay+"&initialVolume="+a.initialVolume},"swfHolder"+c.rndNum)}),a.autoPlay&&
 t.addClass("AudioPause"));ea(c,a,H,e,t,B,C,z,f,b,p,G,k,E,y,h,v);-1==K.indexOf("ipad")&&-1==K.indexOf("iphone")&&-1==K.indexOf("ipod")&&-1==K.indexOf("webos")||t.removeClass("AudioPause");var da=function(){""==c.origParentFloat&&(c.origParentFloat=e.parent().css("float"),c.origParentPaddingTop=e.parent().css("padding-top"),c.origParentPaddingRight=e.parent().css("padding-right"),c.origParentPaddingBottom=e.parent().css("padding-bottom"),c.origParentPaddingLeft=e.parent().css("padding-left"));a.playerWidth!=
 a.origWidth||a.playerWidth>g(window).width()?e.parent().css({"float":"none","padding-top":0,"padding-right":0,"padding-bottom":0,"padding-left":0}):e.parent().css({"float":c.origParentFloat,"padding-top":c.origParentPaddingTop,"padding-right":c.origParentPaddingRight,"padding-bottom":c.origParentPaddingBottom,"padding-left":c.origParentPaddingLeft});var D=e.parent().parent().width();if(e.width()!=D){a.playerWidth=a.origWidth>D?D:a.origWidth;if(e.width()!=a.playerWidth){W("block",c,a,e,H,k,G,E,t,B,
 C,z,f,b,p,y,h,q,l,m,v,x,u,r,n,w);c.audioPlayerHeight=p.height()+q.height()+m.height();c.isMinified&&(c.audioPlayerHeight=q.height()+m.height());e.height(c.audioPlayerHeight);c.wrapperHeight=c.audioPlayerHeight+k.height()+a.historyTopPos;if(!a.showHistory||!a.showHistoryOnInit||c.isMinified||0>k.css("margin-top").substring(0,k.css("margin-top").length-2))c.wrapperHeight=c.audioPlayerHeight;y.css({width:e.width()+"px",height:c.wrapperHeight+"px"});h.width(a.playerWidth-2*a.historyPadding);k.css({width:e.width()+
 "px",top:c.audioPlayerHeight+a.historyTopPos+"px"});G.width(e.width());O(c,a,e,H,k,G,E,t,B,C,z,f,b,p,y,h)}a.playerWidth<g(window).width()&&e.parent().css({"float":c.origParentFloat,"padding-top":c.origParentPaddingTop,"padding-right":c.origParentPaddingRight,"padding-bottom":c.origParentPaddingBottom,"padding-left":c.origParentPaddingLeft})}},X=!1;g(window).on("resize",function(){var D=!0;-1!=A&&9==A&&0==c.windowWidth&&(D=!1);c.windowWidth==g(window).width()?(D=!1,a.windowCurOrientation!=window.orientation&&
 -1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,D=!0)):c.windowWidth=g(window).width();a.responsive&&D&&(!1!==X&&clearTimeout(X),X=setTimeout(function(){da()},300))});a.responsive&&da()})};g.fn.audio6_html5.defaults={radio_stream:"http://194.232.200.150:80/;",radio_name:"Idobi Anthm",url_custom_metdata_file:"",metadata_file_type:"",playerWidth:335,imageHeight:335,skin:"whiteControllers",initialVolume:1,autoPlay:!0,loop:!0,playerBg:"#000000",volumeOffColor:"#454545",
 volumeOnColor:"#ffffff",timerColor:"#ffffff",songTitleColor:"#ffffff",authorTitleColor:"#ffffff",lineSeparatorColor:"#636363",radioStationColor:"#ffffff",frameBehindTextColor:"#000000",frameBehindButtonsColor:"#454545",playerBorderSize:0,playerBorderColor:"#000000",sticky:!1,startMinified:!1,showOnlyPlayButton:!1,centerPlayer:!1,iceCastFirst:!1,showFacebookBut:!0,facebookAppID:"",facebookShareTitle:"HTML5 Radio Player With History - Shoutcast and Icecast",facebookShareDescription:"A top-notch responsive HTML5 Radio Player compatible with all major browsers and mobile devices.",
 facebookShareImage:"",showVolume:!0,showTwitterBut:!0,showRadioStation:!0,showTitle:!0,showHistoryBut:!0,showHistory:!0,showHistoryOnInit:!0,translateReadingData:"reading history...",historyTranslate:"HISTORY - latest played songs",historyTitleColor:"#858585",historyTopPos:0,historyBgColor:"#ebebeb",historyRecordBgColor:"transparent",historyRecordBottomBorderColor:"transparent",historyRecordSongColor:"#000000",historyRecordSongBottomBorderColor:"#d0d0d0",historyRecordAuthorColor:"#6d6d6d",numberOfThumbsPerScreen:3,
 historyPadding:16,preserveOriginalUpperLowerCase:!1,responsive:!0,historyRecordTitleLimit:25,historyRecordAuthorLimit:36,nowPlayingInterval:35,grabLastFmPhoto:!0,optional_images_path:"",azuracast_api_nowplaying_url:"",azuracast_get_image:!1,mscp_pro_api_url:"",pathToAjaxFiles:"",noImageAvailable:"noimageavailable.jpg",lastFMApiKey:"",lastFMSecret:"",origWidth:0,isSliderInitialized:!1,isProgressInitialized:!1,isPlaylistSliderInitialized:!1}})(jQuery);
